import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { TaskStore } from "../storage/task-store.js";
import { Store } from "../storage/store.js";
import fs from "node:fs";
import path from "node:path";

export function registerAgentTools(
  server: McpServer,
  store: Store,
  taskStore: TaskStore,
  projectRoot: string
) {
  const agentsDir = path.join(projectRoot, ".claude", "agents");

  function slugify(title: string): string {
    return title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 50);
  }

  // task_agent_create — create a .claude/agents/ file for a task
  server.tool(
    "task_agent_create",
    "Create a Claude Code agent file (.claude/agents/) for a task. The agent has full task context and can be launched with /agents in any session.",
    {
      taskId: z.string().describe("Task ID or title fragment"),
      constraints: z.array(z.string()).optional().describe("Specific constraints or rules for this task"),
      testCommand: z.string().optional().describe("Command to run tests for this task"),
    },
    async ({ taskId, constraints, testCommand }) => {
      const config = await store.getConfig();
      const task = await taskStore.resolve(taskId, config.activeProjectId ?? undefined);
      if (!task) {
        return { content: [{ type: "text", text: `Task not found: ${taskId}` }] };
      }

      const slug = slugify(task.title);
      const agentFileName = `task-${slug}.md`;
      const agentPath = path.join(agentsDir, agentFileName);

      // Build agent content
      const lines: string[] = [
        `# Task: ${task.title}`,
        "",
        `> Auto-generated by SoloBoard for task ${task.id}`,
        "",
      ];

      if (task.description) {
        lines.push(`## Description`, "", task.description, "");
      }

      // Key files
      const keyFiles = [
        ...(task.context?.relatedFiles ?? []),
        ...task.files,
      ];
      const uniqueFiles = [...new Set(keyFiles)];
      if (uniqueFiles.length > 0) {
        lines.push("## Key Files", "");
        uniqueFiles.slice(0, 15).forEach((f) => lines.push(`- ${f}`));
        lines.push("");
      }

      // Context from previous work
      if (task.context) {
        if (task.context.decisions.length > 0) {
          lines.push("## Decisions Made", "");
          task.context.decisions.forEach((d) => lines.push(`- ${d}`));
          lines.push("");
        }

        if (task.context.remainingWork.length > 0) {
          lines.push("## Remaining Work", "");
          task.context.remainingWork.forEach((w) => lines.push(`- [ ] ${w}`));
          lines.push("");
        }

        if (task.context.suggestedApproach.length > 0) {
          lines.push("## Suggested Approach", "");
          task.context.suggestedApproach.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
          lines.push("");
        }
      }

      // Constraints
      if (constraints && constraints.length > 0) {
        lines.push("## Constraints", "");
        constraints.forEach((c) => lines.push(`- ${c}`));
        lines.push("");
      }

      // Git context
      if (task.branch) {
        lines.push(`## Git`, "", `- Branch: \`${task.branch}\``);
        if (task.commits.length > 0) {
          lines.push(`- Commits: ${task.commits.map((c) => `\`${c}\``).join(", ")}`);
        }
        lines.push("");
      }

      // Test command
      if (testCommand) {
        lines.push("## Testing", "", `Run: \`${testCommand}\``, "");
      }

      // Task tracking integration
      lines.push(
        "## Task Tracking",
        "",
        `This agent is linked to SoloBoard task \`${task.id}\`.`,
        "",
        "When you finish this task, run:",
        "```",
        `/soloboard:task done`,
        "```",
        ""
      );

      // Write agent file
      await fs.promises.mkdir(agentsDir, { recursive: true });
      await fs.promises.writeFile(agentPath, lines.join("\n"), "utf-8");

      // Update task with agent file reference
      await taskStore.update(task.id, { agentFile: agentFileName } as any);

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({
              ok: true,
              taskId: task.id,
              agentFile: agentFileName,
              agentPath: `.claude/agents/${agentFileName}`,
              usage: `Launch with: /agents then select "${agentFileName}"`,
            }),
          },
        ],
      };
    }
  );

  // task_agent_delete — cleanup agent file when task is done
  server.tool(
    "task_agent_delete",
    "Delete the agent file for a completed task. Cleans up .claude/agents/.",
    {
      taskId: z.string().describe("Task ID or title fragment"),
    },
    async ({ taskId }) => {
      const config = await store.getConfig();
      const task = await taskStore.resolve(taskId, config.activeProjectId ?? undefined);
      if (!task) {
        return { content: [{ type: "text", text: `Task not found: ${taskId}` }] };
      }

      if (!task.agentFile) {
        return { content: [{ type: "text", text: `No agent file for task: ${task.title}` }] };
      }

      const agentPath = path.join(agentsDir, task.agentFile);
      try {
        await fs.promises.unlink(agentPath);
      } catch {
        // File already deleted or doesn't exist
      }

      await taskStore.update(task.id, { agentFile: null } as any);

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({ ok: true, taskId: task.id, deleted: task.agentFile }),
          },
        ],
      };
    }
  );
}
